.TH dadosAtomoslib 3 "07/2009" "Versao 1.0"

.SH NOME

dadosAtomoslib \- dados atômicos


.SH DESCRICAO
.B dadosAtomoslib
é uma biblioteca que armazena os dados atomicos dos isótopos mais comuns dos elementos da tabela periódica. É organizado da seguinte forma:
.PP
.I Simbolo
.br
.I Nome
.br
.I Numero Atomico
.br
.I Massa
.br
.I Abundancia
.br
---
.PP
, onde
.I Simbolo
corresponde ao símbolo atômico do elemento se for o isótopo mais abundante (ou mais estável se for elemento artificial) ou é o numero de massa seguido do simbolo atômico para os outros isótopos,
.I Nome
corresponde ao nome do elemento se for o isótopo mais abundante (ou mais estável se for elemento artificial) ou o nome seguido do número de massa,
.I Numero Atomico
corresponde ao número atômico do elemento,
.I Massa
corresponde a massa, em unidades de massa atomica relativa ao isótopo 12 do carbono, e 
.I Abundancia
é a abundância relativa do isótopo.


.SH BUGS
Não são conhecidos bugs para esta biblioteca. Favor contatar o autor se bugs forem encontrados.


.SH VEJA TAMBÉM
.SS Referências
.PP
http://physics.nist.gov/PhysRefData/Compositions/


.SH AUTOR
Yuri Alexandre Aoto - yurikungfu@gmail.com; yuri.aoto@usp.br


.SH COPYRIGHT
Copyright
2009
Yuri Alexandre Aoto
.PP
Esta biblioteca é livre e pode ser utilizada, copiada e modificada a vontade. A utilização e a garantia da autenticidade destes dados ou de qualquer versão modificada é de total responsabilidade do usuário.
