#!/bin/usr/perl

use strict;
use warnings;

die "Give the name of atomic data fle" if (scalar @ARGV < 1);

my $at_data_file = $ARGV[0];
if(scalar @ARGV >= 1){$= = $ARGV[1];}

open (AT_FILE, "<", $at_data_file) or die "Cannot open $at_data_file: $!";

my $symbol;
my $name;
my $Z;
my $mass;
my $abundance;

print "Atomic data,\n";
print "from file $at_data_file\n";
print "Generated by $0\n\n";

format STDOUT_TOP =
Symbol        Name        Z     Mass (based on 12C)    abundance
------  ----------------  ---   -------------------    ---------
.

$^L = "\n";

format STDOUT =
@<<<<< @||||||||||||||||| @<<<  @<<<<<<<<<<<<<         @<<<<<<<<
$symbol, $name, $Z , $mass, $abundance
.

while (<AT_FILE>){

    if(not /^!/){
	
	$symbol = $_;
	$name = <AT_FILE>;
	$Z = <AT_FILE>;
	$mass = <AT_FILE>;
	$abundance = <AT_FILE>;

	($mass,my$trash) = split(/( )*\(/,$mass);
	($abundance,$trash) = split /( )*\(/,$abundance;

	chomp $symbol;
	chomp $name;
	chomp $Z;
	chomp $mass;
	chomp $abundance;
	
write;

	$trash = <AT_FILE>;

    }
}
